name = input("what is your name?: ")
age = (input("how old are you?: "))
fav_col = input("what is your favourite colour?: ")
fav_tv = input("what is your favourite tv show?: ")
print(type(age))
age = int(age)
print(type(age))
print(f"\nMy name is {name}. I am {age} years old, my favourite colour is {fav_col}, and my favourite TV show is {fav_tv}.")
